### ISSUE TITLE
Plan to support Python 3.x?

### ISSUE THREAD

**Issue by fukatani** [koreyou/chainerboard#14]
Hi!
Thanks to release such a nice tool :smile: .

Do you have any plan to support Python 3.4?
I want to call chainerboard from my tool. (https://github.com/fukatani/ChainerWing)
But unfortunately, ChainerWing depends on PyQt5 and it works Python >= 3.5.

**Comment by koreyou** [comment]
Thanks for your interest.
I don't think it's difficult to make it work on Python 3, so I will quickly implement it for next release.

Just to note, though, I do not know if I will maintain this project too long, with the release of the official Chainer UI.

**Comment by fukatani** [comment]
Thank you for response!

This repository is wonderful, especially where the code changes are small.
But actually, I started to use Chainer UI.

**Comment by koreyou** [comment]
This feature is incorporated in ce1b3bdc6eeabfe4a947cb54b70c3c156d220def .
And is available in 0.1.5.
